// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_XF3RJW1uzcVkrFmceJHDoUpy-JNpZ8',
    appId: '1:1056640787763:web:386f34cd3179bdb1d9ca46',
    messagingSenderId: '1056640787763',
    projectId: 'absensi-a010a',
    authDomain: 'absensi-a010a.firebaseapp.com',
    storageBucket: 'absensi-a010a.appspot.com',
    measurementId: 'G-1JV1YJ27ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHLwdWEkd_cnHuPrbPSXjfyymL5BJxPY',
    appId: '1:1056640787763:android:1e90a93370c023a0d9ca46',
    messagingSenderId: '1056640787763',
    projectId: 'absensi-a010a',
    storageBucket: 'absensi-a010a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsBSmYI4zK0bKRsy7fW9uZrdC-EkbKUo',
    appId: '1:1056640787763:ios:5a258a44c2fd897cd9ca46',
    messagingSenderId: '1056640787763',
    projectId: 'absensi-a010a',
    storageBucket: 'absensi-a010a.appspot.com',
    iosBundleId: 'com.example.hyperUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsBSmYI4zK0bKRsy7fW9uZrdC-EkbKUo',
    appId: '1:1056640787763:ios:5a258a44c2fd897cd9ca46',
    messagingSenderId: '1056640787763',
    projectId: 'absensi-a010a',
    storageBucket: 'absensi-a010a.appspot.com',
    iosBundleId: 'com.example.hyperUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg_XF3RJW1uzcVkrFmceJHDoUpy-JNpZ8',
    appId: '1:1056640787763:web:11439ac437757b9ed9ca46',
    messagingSenderId: '1056640787763',
    projectId: 'absensi-a010a',
    authDomain: 'absensi-a010a.firebaseapp.com',
    storageBucket: 'absensi-a010a.appspot.com',
    measurementId: 'G-9H6HR4PCMJ',
  );
}
